theme: jekyll-theme-cayman
title: ViFi-CLIP
description: A simple baseline to adapt CLIP for video action recognition tasks. ViFi-CLIP (Video Fintuned CLIP) performs competitive to more complex approaches having dedicated components designed to model temporal information in videos.
